name: zinger
favicon: null
layout_spectrum: 0.50049
typography_spectrum: 0.42284
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7cd47'
    - '#673d17'
    - '#170e05'
    - '#ab4b19'
    - '#f27316'
  brandStrength: 0.5077005578204989
  lightness: 0.05054790060967207
  saturation: 0.6061612232588232
  rhythmicContrast: 0.2916393482591957
purpose: []
